### PR TITLE
feat: added pkgRoot option

### LINKED ISSUE #32: Setting package root
Hi,

I've a github project that is pushing multiple packages (npm, vsce, etc...)
Each are built to an `out` folder with custom `package.json`

For npm, I define the path as:
```json
    [
      "@semantic-release/npm",
      {
        "pkgRoot": "./out/linter"
      }
    ],
```

But I cannot find a similar setting for vsce, which result in the plugin publishing the root sources instead of `out/vscode`, which basically publishes an unusable package.

I wonder how can that be done using this plugin?

### PR DESCRIPTION
**Pull request by OmarTawfik**
Fixes #32

### CODE REVIEW

**Comment by OmarTawfik** [comment]
cc @raix @felixfbecker

My main concern is that I have no idea how to test these changes, unless it got merged, published to npm, and then tested it in my own build.

**Comment by raix** [comment]
@OmarTawfik awesome! I’ll have a look later this weekend

I you can use ‘npm link’ in the package folder - then use ‘npm link semantic-release-vsce’ In the extension (maybe comment out the actual publish if needed in code while testing)

(A testsuit would have been nice for sure)

**Comment by felipecrs** [comment]
@OmarTawfik could you please rebase your PR and add the tests?

**Review by felipecrs — CHANGES_REQUESTED** [review]
@OmarTawfik Thanks so much for the contribution. Could you please rebase your PR and add the tests?

**Pull request closed without merging**
