### PR TITLE
Remove get last release

### LINKED ISSUE #13: Bug semantic-release v12 does break your plugin
Hi There

First of all: Cool!

I just want to check if I do something wrong:

```bash
[Semantic release]: An error occurred while running semantic-release: Error: The "getLastRelease" plugin output if defined, must be an object with a valid semver version in the "version" property and the corresponding git reference in "gitHead" property. Received: { version: '1.8.0' }
    at Object.getLastRelease (/home/travis/build/buehler/typescript-hero/node_modules/semantic-release/lib/plugins/normalize.js:44:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

That's the output of SR when I run it with version 12.

Is there something missing?

(package.json):
```json
"release": {
    "verifyConditions": [
      "semantic-release-vsce",
      "@semantic-release/github"
    ],
    "getLastRelease": "semantic-release-vsce",
    "publish": [
      {
        "path": "semantic-release-vsce",
        "packageVsix": "your-extension.vsix"
      },
      {
        "path": "@semantic-release/github",
        "assets": "your-extension.vsix"
      }
    ]
  },
````
Cheers

### PR DESCRIPTION
**Pull request by felixfbecker**
Plugins for marketplaces that don't provide `gitHead` are expected to use `@semantic-release/git` instead.

https://github.com/semantic-release/semantic-release/pull/576#issuecomment-358994142

Closes #13

### CODE REVIEW

**Comment by felixfbecker** [comment]
@raix could you investigate why Tavis doesn't run?

**Comment by felixfbecker** [comment]
ping @raix - if you don't have time to maintain atm I would appreciate admin rights so I can investigate the Travis issue

**Comment by raix** [comment]
@felixfbecker travis states: "Build config did not create any jobs." - I'll give you admin

**Comment by raix** [comment]
Seems like the travis file is limited to master?
EDIT: or the "test" stage isn't working - we might have to rework into a test job

**Comment by felixfbecker** [comment]
That did the trick!

**Comment by felixfbecker** [comment]
I assume you are fine with merging this otherwise

**Comment by raix** [comment]
Thanks man!

**Pull request merged**
