### PR TITLE
feat: add support for publishing platform-specific `.vsix`

### PR DESCRIPTION
**Pull request by felipecrs**
## New features

- The existing `packageVsix` option can now be explicitly disabled with `false`
- A new `publishPackagePath` option was added, which allows the use of globs like `*.vsix`
- A new environment variable is supported: `VSCE_TARGET`

Check the documentation for [an example](https://github.com/felipecrs/semantic-release-vsce/blob/multi-arch/README.md#platform-specific-on-github-actions) on how these new features can be combined to achieve platform-specific extensions publishing.

### CODE REVIEW

**Comment by felipecrs** [comment]
@GitMensch and @mbehr1, I haven't started coding the feature yet, but I updated the documentation with what I have in mind.

Would you mind taking a look at it, to see if the approach is acceptable?

Any feedback is welcome.

**Comment by mbehr1** [comment]
@felipecrs  yep, useful! I'll try to migrate my workflows to that approach.

**Comment by felipecrs** [comment]
I'll try to merge the PR in the coming days so. :)

**Comment by felipecrs** [comment]
Oh wow, this got so complicated. But it's finally coming to an end.

**Pull request merged**
