### PR TITLE
ci: publish with npm provenance statement

### PR DESCRIPTION
**Pull request by dsanders11**
It'd be great if this package published with [npm provenance statements](https://docs.npmjs.com/generating-provenance-statements). Since publishing is already automated and uses GitHub Actions, I believe these are the only changes needed.

### CODE REVIEW

**Comment by felipecrs** [comment]
That's an easy win, thank you.

BTW, I should make the next release this week.

**Comment by dsanders11** [comment]
@felipecrs, great to hear. Could you consider bumping to `@semantic-release/error@^4.0.0` before the next release? That's the first version of the package was published with a provenance statement.

**Comment by felipecrs** [comment]
Yes, it's on my plans already (I will need to move to ESM).

**Comment by dsanders11** [comment]
@felipecrs, thanks for the new release! Just a heads up, your latest commits to this repo aren't signed commits, unlike the previous ones. You may want to turn on a ruleset for this repo to enforce signed commits.

**Comment by felipecrs** [comment]
That's a good catch. It happened because I bypassed PRs for some small commits testing GitHub actions changes. I don't have commit signing set up in my dev machine (yet). And by merging with a PR through squashing, the new commit ends up signed automatically. I'll try to avoid bypassing PRs next times.

**Pull request merged**
